### ISSUE TITLE
Please help me out!Thank you!!!

### ISSUE THREAD

**Issue by angeltcy** [harismuneer/Clinic-Management-System-ASP.NET#2]
Hello,I'm a student in learning management system.I'm very interested in this Clinic-Management-System.And l've installed it on my computer.
But l have met a problem now. Every time I, as a patient, want to sent request to the doctor(take appointment), it shows"there was some error in sending to the doctor".I don't know what's wrong and feel confused about it. 
So if you can help me out,I'll be very appreciate.I really hope your reply or more conveniently that you can contact me with my email: 1174183809@qq.com
Thank you so much!!! @harismuneer

**Comment by Hassaan-Elahi** [comment]
You can check your connection strings in the DAL file.  Make sure you used
the correct database name.

**Comment by angeltcy** [comment]
Thank you for your reply.
I have checked that the database name is right.All operations are done well except send request to the doctor.The data can't be input in the appointment table.I don't know where's the problem.Do you have some idea?
Thanks a lot!
